### ISSUE TITLE
garbled chars shown on font installation panels

### ISSUE THREAD

**Issue by ryochin** [kazesawa/kazesawa#1]
Something seems wrong on my OSX 10.11.2, is this an expected situation??

![screenshot_335](https://cloud.githubusercontent.com/assets/45498/11913792/7956789e-a6b3-11e5-888a-955c5a935aac.png)

**Comment by polamjag** [comment]
Thank you for trying this font! :smile:

There are no such problem in my environment (10.11.2). Tryed installation panel, quick look and preview in Finder but all are working well.

<img width="400" alt="scr 2015-12-20 3 10 50" src="https://cloud.githubusercontent.com/assets/685936/11914533/4f551384-a6c7-11e5-8640-2fe8bc579bb2.png">
![scr 2015-12-20 3 10 59](https://cloud.githubusercontent.com/assets/685936/11914534/51296b6a-a6c7-11e5-9be8-1ee614dfee81.png)
<img width="412" alt="scr 2015-12-20 3 12 11" src="https://cloud.githubusercontent.com/assets/685936/11914542/7d3d1364-a6c7-11e5-8915-a4ba40067871.png">

Could you try installing that and using it in some applications such as Web Browsers, Pages or Keynote?

**Comment by ryochin** [comment]
（日本語のフォントなのだから無理に英語にする必要ありませんでしたね・・）

インストールしていくつかのソフトで試したところ、表示に問題はないようです。QuickLook 等 Finder 上でも正しく表示されますから、FontBook 単体の問題かもしれません。

フォント周りでもしかして関係ありそうなソフトとしては TexLive （組版ソフト）を入れているくらいです。

環境依存の可能性が高そうですし、あまり気にしなくてもよさそうですね。

**Comment by polamjag** [comment]
表示に問題はないということで、とりあえずは何よりです。TeXLive が原因になるというのはあまり考えにくい感じがします。

ひとまずこのまま様子見ということにして、また何か問題があれば教えていただけるとありがたいです。
